## Using scipy to compute the 'ground-truth' matrices

In [6]:
import scipy
from scipy.stats import multivariate_normal
from scipy.ndimage import convolve
import numpy as np

In [18]:
def create_2d_gaussian_kernel(kernel_size, sigma=1.0):
    """Create a 2D Gaussian kernel with the specified size and sigma."""
    # Create a grid of (x,y) coordinates at which to evaluate the kernel
    kernel_range = np.arange(-kernel_size // 2 + 1, kernel_size // 2 + 1)
    x, y = np.meshgrid(kernel_range, kernel_range)
    
    # Calculate the 2D Gaussian
    pos = np.empty(x.shape + (2,))
    pos[:, :, 0] = x
    pos[:, :, 1] = y
    kernel = multivariate_normal(mean=[0, 0], cov=np.eye(2) * sigma**2).pdf(pos)
    
    # Normalize the kernel so the sum of all elements is 1
    kernel /= kernel.sum()
    
    return kernel

In [19]:
def create_mean_kernel(kernel_size):
    average_kernel = np.ones((kernel_size, kernel_size), dtype=np.float32) / (kernel_size * kernel_size)
    
    return average_kernel

### Test 1 : Check Computation

In [21]:
kernel_size = 3  # Specify the size of the kernel (must be an odd number)
sigma = 1.0

original_array = np.array([[0,0,0,0,0],
                          [0,0,0,0,0],
                         [0,0,255,0,0],
                         [0,0,0,0,0],
                         [0,0,0,0,0]])

mean_kernel_2d = create_mean_kernel(kernel_size)
gaussian_kernel_2d = create_2d_gaussian_kernel(kernel_size, sigma)

# Now convolve the original array with the 3D Gaussian kernel
filtered_array_mean = convolve(original_array, mean_kernel_2d, mode='nearest')
filtered_array_gaussian = convolve(original_array, gaussian_kernel_2d, mode='nearest')

In [22]:
filtered_array_mean

array([[ 0,  0,  0,  0,  0],
       [ 0, 28, 28, 28,  0],
       [ 0, 28, 28, 28,  0],
       [ 0, 28, 28, 28,  0],
       [ 0,  0,  0,  0,  0]])

In [23]:
filtered_array_gaussian

array([[ 0,  0,  0,  0,  0],
       [ 0, 19, 31, 19,  0],
       [ 0, 31, 52, 31,  0],
       [ 0, 19, 31, 19,  0],
       [ 0,  0,  0,  0,  0]])

In [33]:
kernel_size = 5  # Specify the size of the kernel (must be an odd number)
sigma = 1.0

original_array = np.array([[0,0,0,0,0],
                          [0,0,0,0,0],
                         [0,0,255,0,0],
                         [0,0,0,0,0],
                         [0,0,0,0,0]])

mean_kernel_2d = create_mean_kernel(kernel_size)
gaussian_kernel_2d = create_2d_gaussian_kernel(kernel_size, sigma)

# Now convolve the original array with the 3D Gaussian kernel
filtered_array_mean = convolve(original_array, mean_kernel_2d, mode='nearest')
filtered_array_gaussian = convolve(original_array, gaussian_kernel_2d, mode='nearest')

In [34]:
filtered_array_mean

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [35]:
filtered_array_gaussian

array([[ 0,  3,  5,  3,  0],
       [ 3, 15, 25, 15,  3],
       [ 5, 25, 41, 25,  5],
       [ 3, 15, 25, 15,  3],
       [ 0,  3,  5,  3,  0]])

### Test 2 : Check Boundary

In [39]:
kernel_size = 3  # Specify the size of the kernel (must be an odd number)
sigma = 1.0

original_array = np.array([[255,0,0,0,255],
                          [0,0,0,0,0],
                         [0,0,0,0,0],
                         [0,0,0,0,0],
                         [255,0,0,0,255]])

mean_kernel_2d = create_mean_kernel(kernel_size)
gaussian_kernel_2d = create_2d_gaussian_kernel(kernel_size, sigma)

# Now convolve the original array with the 3D Gaussian kernel
filtered_array_mean = convolve(original_array, mean_kernel_2d, mode='nearest')
filtered_array_gaussian = convolve(original_array, gaussian_kernel_2d, mode='nearest')

In [40]:
filtered_array_mean

array([[113,  56,   0,  56, 113],
       [ 56,  28,   0,  28,  56],
       [  0,   0,   0,   0,   0],
       [ 56,  28,   0,  28,  56],
       [113,  56,   0,  56, 113]])

In [41]:
filtered_array_gaussian

array([[134,  50,   0,  50, 134],
       [ 50,  19,   0,  19,  50],
       [  0,   0,   0,   0,   0],
       [ 50,  19,   0,  19,  50],
       [134,  50,   0,  50, 134]])

In [42]:
kernel_size = 5  # Specify the size of the kernel (must be an odd number)
sigma = 1.0

original_array = np.array([[255,0,0,0,255],
                          [0,0,0,0,0],
                         [0,0,0,0,0],
                         [0,0,0,0,0],
                         [255,0,0,0,255]])

mean_kernel_2d = create_mean_kernel(kernel_size)
gaussian_kernel_2d = create_2d_gaussian_kernel(kernel_size, sigma)

# Now convolve the original array with the 3D Gaussian kernel
filtered_array_mean = convolve(original_array, mean_kernel_2d, mode='nearest')
filtered_array_gaussian = convolve(original_array, gaussian_kernel_2d, mode='nearest')

In [43]:
filtered_array_mean

array([[91, 61, 61, 61, 91],
       [61, 40, 40, 40, 61],
       [61, 40, 40, 40, 61],
       [61, 40, 40, 40, 61],
       [91, 61, 61, 61, 91]])

In [44]:
filtered_array_gaussian

array([[125,  53,  19,  53, 125],
       [ 53,  22,   8,  22,  53],
       [ 19,   8,   3,   8,  19],
       [ 53,  22,   8,  22,  53],
       [125,  53,  19,  53, 125]])